"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](fg:#769ff0)\
$directory\
$git_branch\
$git_status\
$nodejs\
$golang\
$terraform\
$cmd_duration\
\n$character"""

add_newline = false

[character]
success_symbol = '[❯](bold #bbbbbb)'
error_symbol = '[✗](bold red)'

[cmd_duration]
min_time = 0
format = "[ $duration ]($style)"

[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "../"

[git_branch]
symbol = "⎇"
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol $branch ]($style)'

[git_status]
disabled = true

[nodejs]
symbol = ""
style = "fg:#c5e5b4 bg:#2a3145"
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ""
style = "fg:#5dc9e2 bg:#2a3145"
format = '[ $symbol ($version) ]($style)'

[terraform]
symbol = " "
style = "fg:#b28fce bg:#2a3145"
format = '[ $symbol $workspace ]($style)'

[package]
disabled = true
